#!/usr/bin/env bash

# conky editor: will find conky files in ~/.config/conky, and allow opening them
# Original concept by damo <damo@bunsenlabs.org> for BunsenLabs Linux, April 2015
# Re Written by Nathaniel Maia For ArchLabs, December 2017

readonly TITLE="ArchLabs Conky Edit"
readonly TEXT="<big>Select Conkys to edit from the list</big>"
readonly ICON="--window-icon=/usr/share/icons/ArchLabs-Light/64x64/places/distributor-logo-archlabs.png"
readonly CHECKLIST="zenity --width=400 --height=500 $ICON --list --checklist --multiple"

if [[ -d $HOME/.config/conky ]]; then
	for file in $(find -L "$HOME/.config/conky" -maxdepth 4 -type f); do
		name="${file##*/}"
		[[ $name = *conkyrc || $name = *conky ]] && LIST+="FALSE $name "
	done
else
	MSG="<big>No conky configs found</big>\n\nConfigs must be located in:\n$HOME/.config/conky"
	zenity --info --width=300 --height=150 $ICON --text="$MSG" &>/dev/null ; exit 0
fi

ANSWER="$($CHECKLIST --title="$TITLE" --text="$TEXT" --separator=" " --column="Select" --column="Conky Name" $LIST)"

if [ $? -ne 0 ]; then
	exit 0
else
	for name in $ANSWER; do
		for file in $FILES; do
			if [[ "${file##*/}" = "$name" ]]; then
				if hash exo-open &>/dev/null; then
					(exo-open "$file" &)
				elif hash termite &>/dev/null; then
					(termite -e "$EDITOR $file" &>/dev/null)
				elif hash st &>/dev/null; then
					(st -e $EDITOR $file &)
				elif hash urxvt &>/dev/null; then
					(urxvt -e "$EDITOR $file" &)
				fi
				break
			fi
		done
	done
fi

exit 0
