#!/usr/bin/env bash

# al-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
# Written for ArchLabs by Nathaniel Maia <natemaaia10@gmail.com> 2017

readonly CPATH="$HOME/.config/polybar"
CONFIG="$CPATH/config"

case "$1" in
    -h|--help)
		cat << EOF
al-polybar-pipemenu - an openbox pipe menu for polybar

Options:
    -h --help   show this message

If al-polybar-pipemenu is called with no options (the usual method),
it will output an xml openbox pipemenu for handling polybar sessions,
and editing configuration files.
EOF
		exit 0
		;;
esac

if ! . /usr/lib/archlabs/common/al-include 2>/dev/null; then
    echo "al-polybar-pipemenu: error: failed to source /usr/lib/archlabs/common/al-include" >&2
	exit 1
fi

Editmenu() {
	if pidof polybar >/dev/null 2>&1; then
		menuSeparator
		menuSubmenu "RunningBar" "Running Bars"
		while read -r pid cmd; do
			if [[ ${cmd%% *} = polybar ]]; then
				CONF=${cmd##* }
				[[ $CONF = polybar ]] && CONF=$CONFIG
				if hash exo-open &>/dev/null; then
					menuItem "$CONF" "exo-open $CONFIG"
				elif hash termite &>/dev/null; then
					menuItem "$CONF" "termite -e '$EDITOR $CONFIG'"
				elif hash st &>/dev/null; then
					menuItem "$CONF" "st -e $EDITOR $CONFIG"
				elif hash urxvt &>/dev/null; then
					menuItem "$CONF" "urxvt -e '$EDITOR $CONFIG'"
				fi
			fi
		done <<< "$(pgrep -a polybar)"
		menuSubmenuEnd
	fi
}

Configs() {
	menuSubmenu "EditConfigs" "Edit Configs"
	if hash al-polybar-edit >/dev/null 2>&1; then
		menuItem "Edit Configs" "al-polybar-edit"
	fi
	Editmenu
	menuSubmenuEnd
}

Launchmenu() {
	if hash al-polybar-session &>/dev/null && [[ -f "$CPATH/sessions/openbox-sessionfile" ]]; then
		if pidof polybar >/dev/null 2>&1; then
			menuItem "Restart Polybar" "al-polybar-session"
		else
			menuItem "Start Polybar" "al-polybar-session"
		fi
	fi
	if type al-polyzen &>/dev/null; then
		menuItem "Polybar Session GUI" "al-polyzen"
	fi
}

Killmenu() {
	if pidof polybar >/dev/null 2>&1; then
		menuItem "Stop Bars" "pkill polybar"
	fi
}

menuStart "Polybarmenu" "Polybar"
Launchmenu
Killmenu
Configs
menuEnd
